name: Compile all LaTeX file
on: [pull_request, workflow_dispatch]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4.1.0
      - uses: teatimeguest/setup-texlive-action@v2.2.5
      - run: ls >> ls.txt
  
