name: Compile all LaTeX file
on: [pull_request, workflow_dispatch]
jobs:
  compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - uses: actions/setup-python@v4.1.0
      - uses: teatimeguest/setup-texlive-action@v2.2.5
      - run: echo $PWD
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./
  
